export default {
    en: {
        "invite.invite": "Invite",
        "invite.begin": "scroll to begin",
        "invite.drop": "Drop",
        "invite.p1": "ArtDAO has been working over the past year on our own platform on Fuel - a new execution layer for Ethereum which we believe offers a powerful opportunity to expand the possibilities of digital art. Removing the friction and costs of Eth without losing the ability to easily secure assets long term seamlessly back onto mainnet. In the process, enabling us to creating a new kind of artist driven infrastructure which works to develop new means to discover, support, curate and connect people with digital art and artistry.",
        "invite.p2": "To begin this project we are launching a new series of curated drops, working with artists we believe have powerful artistic visions to bring them to life as new collections on our platform which bring it to life across a series of new artworks created, an immersive online zine and physical exhibition.",
        "invite.p3": "For Hyperescapismo, we have been working with Femzor & Occulted for the past 3 months to explore how transversal forms of digital technology intersect between the possible sublimation of our imaginations and, on the other hand, as a means of digression, subterfuge, and creation: a reimagining of the possible.",
        "invite.p4": "We have chosen together a group of 20 artists who we feel have each found a unique means of expression amongst a growing expanse of technological tools and across an array of blogs, internet forums, social media networks and game worlds. Artists who have found a means to go beyond the conformity and sterility of post-modernism and embrace a relationship with technology which surpasses simple acts of consumption to become a creative experience that brings together their own inner worlds, works of art and subterranean spaces of virtuality.",
        "invite.p5": "In receiving this we extend an invite for you to join us in this drop alongside 19 other artists. Producing a new 1/1 work to be minted on the artdao platform for auction, as well as shown over a month long exhibition at Caroço in São Paulo from march to april, and within the virtual zine experience we have been working with Occulted & Femzor to create.",

    },
    pt: {
        "invite.invite": "Convite",
        "invite.begin": "percorrer para começar",
        "invite.drop": "Drop",
        "invite.p1": "A ArtDAO está trabalhando há um ano na nossa própria plataforma no Fuel - uma nova camada de execução pro Ethereum. A gente acredita que isso oferece uma oportunidade incrível de expandir as possibilidades da arte digital. Diminuindo a burocracia e os custos do Ethereum sem perder a capacidade de garantir a segurança dos ativos a longo prazo e voltar pro mainnet de forma tranquila. Nesse processo, a gente está criando uma nova infraestrutura liderada por artistas que desenvolve novas formas de descobrir, apoiar, curar e conectar as pessoas com a arte digital e os artistas.",
        "invite.p2": "Pra começar esse projeto, estamos lançando uma série nova de drops, trabalhando com artistas enquanto curadores e que acreditamos terem visões artísticas poderosas pra trazer à vida novas coleções na nossa plataforma. Isso vai ganhar vida através de uma série de novas obras, uma zine online imersiva e uma exposição física.",
        "invite.p3": "No Hyperescapismo, trabalhamos com Femzor & Occulted nos últimos 3 meses pra explorar como as formas transversais de tecnologia digital se cruzam entre a possível sublimação das nossas imaginações e, por outro lado, como um meio de digressão, subterfúgio e criação: uma re-imaginação do possível.",
        "invite.p4": "Escolhemos um grupo de 20 artistas que acreditamos terem encontrado um meio único de expressão em meio de uma expansão crescente de ferramentas tecnológicas e através de uma variedade de blogs, fóruns de internet, redes sociais e mundos de jogos. Artistas que foram além da conformidade e esterilidade do pós-modernismo e abraçaram uma relação com a tecnologia que supera simples atos de consumo para se tornar uma experiência criativa que une seus próprios mundos internos, obras de arte e espaços subterrâneos de virtualidade.",
        "invite.p5": "Ao receber isso, te convidamos pra te juntar a nós nesse drop junto com outros 19 artistas. Produzindo uma nova obra 1/1 para ser cunhada na plataforma ArtDAO para leilão, além de ser exibida numa exposição durante o mês de março a abril de 2024 no Caroço em São Paulo, e dentro da experiência do zine virtual que estamos criando com Occulted & Femzor.",
    },
  };